### ISSUE TITLE
Error maps from the API return as `[object Object]`

### ISSUE THREAD

**Issue by timhwang21** [absinthe-graphql/absinthe-socket#39] opened 2019-03-19 19:28 UTC
Seems related to #20 and #29. Also related to phoenixframework/phoenix#3323.

It seems like the various `createFooError(errorMessage)`s and the various upstream handlers all expect `errorMessage` to be a string. If my API returns a map instead we get `[object Object]`.

In the other ticket I filed, I post a solution for preprocessing the error message into a string. However, I was wondering if it's reasonable to just check for stringiness in this library, and call `JSON.serialize` on the message if it's not a string?

A simple example would be changing [`createRequestError()`](https://github.com/absinthe-graphql/absinthe-socket/blob/a80076a909e62ede26334deab3a5e045490230d4/packages/socket/src/pushRequestUsing.js#L30) to be:

```typescript
const createRequestError = message =>
  new Error(`request: ${typeof message === 'string' ? JSON.stringify(message) : message}`)
```

(Would obviously benefit from more abstraction!)

**Comment by mgtitimoli** [comment] 2019-03-19 20:49
Message must be string by [spec](https://facebook.github.io/graphql/draft/#sec-Errors).

We could consider adding support to [extensions](https://facebook.github.io/graphql/draft/#example-fce18).

**Comment by mgtitimoli** [comment] 2019-03-19 20:53
Duplicate of #29 (Let's follow the discussion there)

**Closed by mgtitimoli** 2019-03-19 20:53 UTC
