### ISSUE TITLE
Upgrade to latest apollo-client, zen-observable?

### ISSUE THREAD

**Issue by aksonov** [absinthe-graphql/absinthe-socket#19] opened 2018-04-12 10:36 UTC
zen-observable 0.6.0 and other used libraries are outdated, could you upgrade or at least use ^0.6.0 instead of 0.6.0 ?

Following happens if a client sends invalid graphql query to the server (and the server returns 'error' response):
![simulator screen shot - iphone 7 - 2018-04-10 at 09 54 56](https://user-images.githubusercontent.com/1321329/38672300-0ceab096-3e4e-11e8-8721-8f3eef5c516e.png)

**Comment by mgtitimoli** [comment] 2018-05-12 01:46
Closing this one, as it's duplicate of #12.

(Thanks for reporting)

**Closed by mgtitimoli** 2018-05-12 01:46 UTC
