### ISSUE TITLE
Error reporting bugged

### ISSUE THREAD

**Issue by gjaldon** [absinthe-graphql/absinthe-socket#12] opened 2017-12-13 09:53 UTC
I'm using apollo on the frontend and absinthe on the backend. I experienced an issue where I was submitting a mutation to the backend but it would not go through. I'd get a totally different unrelated error like:
![error](https://www.evernote.com/shard/s280/sh/68c5e1e3-d9be-4327-9cc6-896c3d8d6fba/393583b1bf9cd875/res/69e274bf-6731-4a6d-9a1a-75cf4cc2d541/skitch.png)

Turns out the actual error in the backend was that the input was incorrect (a required argument was not provided). This error was not reported because I was getting `Uncaught TypeError: Cannot read property '_observer' of undefined` instead. That undefined error is the one being reported because `subscription` is undefined in the below code:

```javascript
   // zen-observable v0.6.0 lines 158-162.
   var subscription = this._subscription;

    // If the stream is closed, throw the error to the caller
    if (subscriptionClosed(subscription))
      throw value;
```

This happens before the actual error value is thrown.

We do not use `zen-observable` directly in our project and is only a dependency of `socket-apollo-link`.

**Comment by mtarnovan** [comment] 2018-01-02 10:55
I'm seeing the same error, but in my case the subscription query is correct and there's no error on the backend.

**Comment by mgtitimoli** [comment] 2018-02-20 19:28
This issue will be fixed on the next release that will be released on March, meanwhile I will attach below a stacktrace taken from the error on a release with sourcemaps:
```
undefined is not an object (evaluating 'subscription._observer')

subscriptionClosed
   zen-observable.js:66:22
error
   zen-observable.js:161:27
<unknown>
   notify.js:6:49
notify
   notify.js:11:29
abortRequest
   pushRequest.js:39:17
onError
   pushRequest.js:43:15
<unknown>
   createPushHandler.js:15:4
matchReceive
   phoenix.js:321:17
<unknown>
   phoenix.js:354:27
trigger
   phoenix.js:614:13
<unknown>
   phoenix.js:436:21
trigger
   phoenix.js:614:13
<unknown>
   phoenix.js:1037:19
onConnMessage
   phoenix.js:1023:18
dispatchEvent
   event-target.js:172:43
<unknown>
   WebSocket.js:237:27
emit
   EventEmitter.js:182:12
__callFunction
   MessageQueue.js:353:47
<unknown>
   MessageQueue.js:118:26
__guardSafe
   MessageQueue.js:316:6
callFunctionReturnFlushedQueue
   MessageQueue.js:117:17
```

**Comment by JesusPuga** [comment] 2018-04-22 01:59
I have a similar problem
has this issue some advance o some temporal solution?

**Comment by southerneer** [comment] 2018-04-23 23:15
Any word on that March release?

**Comment by mgtitimoli** [comment] 2018-04-24 17:13
Hi everyone,

The new version should be released soon, unfortunately the past 2 months I haven't had enough time to move forward with it as we are in the last phase of the product for the company I work for and support my time on absinthe.

I will be able to proceed with the release once we ship the product, and this should be in the next month or so.

My apologies to everyone.

**Comment by nathanqueija** [comment] 2018-05-17 20:32
Does this error prevent apollo's subscriptions from working?

**Comment by MikaAK** [comment] 2018-06-26 11:31
What can I do to fix this?

**Comment by markkanof** [comment] 2018-08-01 04:45
Any updates on this? I'm running into this issue, that seems to be triggered when called resetStore on my Apollo client.

**Comment by rjacobskind** [comment] 2018-10-09 20:40
@mgtitimoli Is there any update on this? I'm seeing this error frequently as well

**Comment by rjacobskind** [comment] 2018-10-10 14:42
I opened a PR to solve this and #15 . Please see below:
https://github.com/absinthe-graphql/absinthe-socket/pull/26

**Comment by rmoorman** [comment] 2018-11-16 14:04
I can confirm that the patch in PR #26 does fix the issue over here! Thank you @mpoeter and @rjacobskind for this! I hope some fix for these problem will be released soon as a working subscription mechanism seems vital for this project.

**Closed** 2018-12-13 21:30 UTC
